version: '3'

services:
  portainer:
    image:  micael11/recipe-book:alpha
    container_name: recipe-book
    restart: unless-stopped
    ports:
      - 8000:80
networks:
  default:
    external: true
    name: nginx-proxy-manager_default 